syntax = "proto3";

//
// Servico responsavel pela comunicacao com o front-end.
//
service Gateway {
    // Ao receber notificacao de lance validado
    rpc OnLanceValidado(OnLanceValidadoRequest) returns (OnLanceValidadoResponse) {}
    // Ao receber notificacao de lance invalidado
    rpc OnLanceInvalidado(OnLanceInvalidadoRequest) returns (OnLanceInvalidadoResponse) {}
    // Ao receber notificacao de vencedor de um leilao
    rpc OnLeilaoVencedor(OnLeilaoVencedorRequest) returns (OnLeilaoVencedorResponse) {}
    // Ao receber notificacao de geracao de link de pagamento
    rpc OnLinkPagamento(OnLinkPagamentoRequest) returns (OnLinkPagamentoResponse) {}
    // Ao receber notificacao do status do pagamento
    rpc OnStatusPagamento(OnStatusPagamentoRequest) returns (OnStatusPagamentoResponse) {}
}

message OnLanceValidadoRequest {
    string leilao_id = 1;
    string client_id = 2;
    string value = 3;
}

message OnLanceValidadoResponse {
    bool ok = 1;
}

message OnLanceInvalidadoRequest {
    string leilao_id = 1;
    string client_id = 2;
    string value = 3;
}

message OnLanceInvalidadoResponse {
    bool ok = 1;
}

message OnLeilaoVencedorRequest {
    string leilao_id = 1;
    string lance_vencedor = 2;
    string cliente_vencedor = 3;
}

message OnLeilaoVencedorResponse {
    bool ok = 1;
}

message OnLinkPagamentoRequest {
    string leilao_id = 1;
    string lance_vencedor = 2;
    string cliente_vencedor = 3;
    string link = 4;
}

message OnLinkPagamentoResponse {
    bool ok = 1;
}

message OnStatusPagamentoRequest {
    string value = 1;
    string status = 2;
    string transaction_id = 3;
    string client_id = 4;
}

message OnStatusPagamentoResponse {
    bool ok = 1;
}
