syntax = "proto3";

//
/// Servico responsavel pelo gerenciamento dos lances.
//
service Lance {
    // Realiza um lance
    rpc OnLance(OnLanceRequest) returns (OnLanceResponse) {}
    // Ao receber notificacao de leilao iniciado
    rpc OnInitLeilao(OnInitLeilaoRequest) returns (OnInitLeilaoResponse) {}
    // Ao receber notificacao de leilao finalizado
    rpc OnEndLeilao(OnEndLeilaoRequest) returns (OnEndLeilaoResponse) {}
}

message OnLanceRequest {
    string leilao_id = 1;
    string client_id = 2;
    string value = 3;
}

message OnLanceResponse {
    bool ok = 1;
    string message = 2;
}

message OnInitLeilaoRequest {
    string id = 1;
    string description = 2;
    float start = 3;
    float end = 4;
}

message OnInitLeilaoResponse {
    bool ok = 1;
}

message OnEndLeilaoRequest {
    string id = 1;
}

message OnEndLeilaoResponse {
    bool ok = 1;
    string leilao_id = 2;
    string cliente_vencedor = 3;
    string lance_vencedor = 4;
}