syntax = "proto3";

/// 
/// Servico responsavel pelo gerenciamento de leiloes.
///
service Leilao {
    // Carrega todos os leiloes
    rpc GetLeiloes(GetLeiloesRequest) returns (GetLeiloesResponse) {}
    // Cria um leilao
    rpc CreateLeilao(CreateLeilaoRequest) returns (CreateLeilaoResponse) {}
}

message LeilaoInstance {
    string id = 1;
    string name = 2;
    string description = 3;
    float value = 4;
    string start = 5;
    string end = 6;
}

message GetLeiloesRequest {
}

message GetLeiloesResponse {
    repeated LeilaoInstance leiloes = 1; 
}

message CreateLeilaoRequest {
    string name = 2;
    string description = 3;
    float value = 4;
    int32 start = 5;
    int32 end = 6;
}

message CreateLeilaoResponse {
    bool ok = 1;
}