# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/leilao.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protocols/leilao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protocols/leilao.proto\"k\n\x0fLeilao_instance\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\r\n\x05start\x18\x05 \x01(\t\x12\x0b\n\x03\x65nd\x18\x06 \x01(\t\"\"\n\x11GetLeiloesRequest\x12\r\n\x05\x65mpty\x18\x01 \x01(\t\"6\n\x12GetLeiloesResponse\x12 \n\x06leilao\x18\x01 \x01(\x0b\x32\x10.Leilao_instance\"7\n\x13\x43reateLeilaoRequest\x12 \n\x06leilao\x18\x01 \x01(\x0b\x32\x10.Leilao_instance\"\"\n\x14\x43reateLeilaoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x82\x01\n\x06Leilao\x12\x39\n\nGetLeiloes\x12\x12.GetLeiloesRequest\x1a\x13.GetLeiloesResponse\"\x00\x30\x01\x12=\n\x0c\x43reateLeilao\x12\x14.CreateLeilaoRequest\x1a\x15.CreateLeilaoResponse\"\x00\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.leilao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEILAO_INSTANCE']._serialized_start=26
  _globals['_LEILAO_INSTANCE']._serialized_end=133
  _globals['_GETLEILOESREQUEST']._serialized_start=135
  _globals['_GETLEILOESREQUEST']._serialized_end=169
  _globals['_GETLEILOESRESPONSE']._serialized_start=171
  _globals['_GETLEILOESRESPONSE']._serialized_end=225
  _globals['_CREATELEILAOREQUEST']._serialized_start=227
  _globals['_CREATELEILAOREQUEST']._serialized_end=282
  _globals['_CREATELEILAORESPONSE']._serialized_start=284
  _globals['_CREATELEILAORESPONSE']._serialized_end=318
  _globals['_LEILAO']._serialized_start=321
  _globals['_LEILAO']._serialized_end=451
# @@protoc_insertion_point(module_scope)
