# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protocols import pagamento_pb2 as protocols_dot_pagamento__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protocols/pagamento_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PagamentoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnWinner = channel.unary_unary(
                '/Pagamento/OnWinner',
                request_serializer=protocols_dot_pagamento__pb2.OnWinnerRequest.SerializeToString,
                response_deserializer=protocols_dot_pagamento__pb2.OnWinnerResponse.FromString,
                _registered_method=True)


class PagamentoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnWinner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PagamentoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.OnWinner,
                    request_deserializer=protocols_dot_pagamento__pb2.OnWinnerRequest.FromString,
                    response_serializer=protocols_dot_pagamento__pb2.OnWinnerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pagamento', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Pagamento', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pagamento(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Pagamento/OnWinner',
            protocols_dot_pagamento__pb2.OnWinnerRequest.SerializeToString,
            protocols_dot_pagamento__pb2.OnWinnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
