# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStub(object):
    """
    Servico responsavel pela comunicacao com o front-end.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnLanceValidado = channel.unary_unary(
                '/Gateway/OnLanceValidado',
                request_serializer=gateway__pb2.OnLanceValidadoRequest.SerializeToString,
                response_deserializer=gateway__pb2.OnLanceValidadoResponse.FromString,
                _registered_method=True)
        self.OnLanceInvalidado = channel.unary_unary(
                '/Gateway/OnLanceInvalidado',
                request_serializer=gateway__pb2.OnLanceInvalidadoRequest.SerializeToString,
                response_deserializer=gateway__pb2.OnLanceInvalidadoResponse.FromString,
                _registered_method=True)
        self.OnLeilaoVencedor = channel.unary_unary(
                '/Gateway/OnLeilaoVencedor',
                request_serializer=gateway__pb2.OnLeilaoVencedorRequest.SerializeToString,
                response_deserializer=gateway__pb2.OnLeilaoVencedorResponse.FromString,
                _registered_method=True)
        self.OnLinkPagamento = channel.unary_unary(
                '/Gateway/OnLinkPagamento',
                request_serializer=gateway__pb2.OnLinkPagamentoRequest.SerializeToString,
                response_deserializer=gateway__pb2.OnLinkPagamentoResponse.FromString,
                _registered_method=True)
        self.OnStatusPagamento = channel.unary_unary(
                '/Gateway/OnStatusPagamento',
                request_serializer=gateway__pb2.OnStatusPagamentoRequest.SerializeToString,
                response_deserializer=gateway__pb2.OnStatusPagamentoResponse.FromString,
                _registered_method=True)


class GatewayServicer(object):
    """
    Servico responsavel pela comunicacao com o front-end.

    """

    def OnLanceValidado(self, request, context):
        """Ao receber notificacao de lance validado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnLanceInvalidado(self, request, context):
        """Ao receber notificacao de lance invalidado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnLeilaoVencedor(self, request, context):
        """Ao receber notificacao de vencedor de um leilao
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnLinkPagamento(self, request, context):
        """Ao receber notificacao de geracao de link de pagamento
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnStatusPagamento(self, request, context):
        """Ao receber notificacao do status do pagamento
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnLanceValidado': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLanceValidado,
                    request_deserializer=gateway__pb2.OnLanceValidadoRequest.FromString,
                    response_serializer=gateway__pb2.OnLanceValidadoResponse.SerializeToString,
            ),
            'OnLanceInvalidado': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLanceInvalidado,
                    request_deserializer=gateway__pb2.OnLanceInvalidadoRequest.FromString,
                    response_serializer=gateway__pb2.OnLanceInvalidadoResponse.SerializeToString,
            ),
            'OnLeilaoVencedor': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLeilaoVencedor,
                    request_deserializer=gateway__pb2.OnLeilaoVencedorRequest.FromString,
                    response_serializer=gateway__pb2.OnLeilaoVencedorResponse.SerializeToString,
            ),
            'OnLinkPagamento': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLinkPagamento,
                    request_deserializer=gateway__pb2.OnLinkPagamentoRequest.FromString,
                    response_serializer=gateway__pb2.OnLinkPagamentoResponse.SerializeToString,
            ),
            'OnStatusPagamento': grpc.unary_unary_rpc_method_handler(
                    servicer.OnStatusPagamento,
                    request_deserializer=gateway__pb2.OnStatusPagamentoRequest.FromString,
                    response_serializer=gateway__pb2.OnStatusPagamentoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """
    Servico responsavel pela comunicacao com o front-end.

    """

    @staticmethod
    def OnLanceValidado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Gateway/OnLanceValidado',
            gateway__pb2.OnLanceValidadoRequest.SerializeToString,
            gateway__pb2.OnLanceValidadoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnLanceInvalidado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Gateway/OnLanceInvalidado',
            gateway__pb2.OnLanceInvalidadoRequest.SerializeToString,
            gateway__pb2.OnLanceInvalidadoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnLeilaoVencedor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Gateway/OnLeilaoVencedor',
            gateway__pb2.OnLeilaoVencedorRequest.SerializeToString,
            gateway__pb2.OnLeilaoVencedorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnLinkPagamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Gateway/OnLinkPagamento',
            gateway__pb2.OnLinkPagamentoRequest.SerializeToString,
            gateway__pb2.OnLinkPagamentoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnStatusPagamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Gateway/OnStatusPagamento',
            gateway__pb2.OnStatusPagamentoRequest.SerializeToString,
            gateway__pb2.OnStatusPagamentoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
