"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import gateway_pb2
import grpc
import grpc.aio
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_GatewayOnLanceValidadoType = typing_extensions.TypeVar(
    '_GatewayOnLanceValidadoType',
    grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceValidadoRequest,
        gateway_pb2.OnLanceValidadoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceValidadoRequest,
        gateway_pb2.OnLanceValidadoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceValidadoRequest,
        gateway_pb2.OnLanceValidadoResponse,
    ],
)

_GatewayOnLanceInvalidadoType = typing_extensions.TypeVar(
    '_GatewayOnLanceInvalidadoType',
    grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceInvalidadoRequest,
        gateway_pb2.OnLanceInvalidadoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceInvalidadoRequest,
        gateway_pb2.OnLanceInvalidadoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceInvalidadoRequest,
        gateway_pb2.OnLanceInvalidadoResponse,
    ],
)

_GatewayOnLeilaoVencedorType = typing_extensions.TypeVar(
    '_GatewayOnLeilaoVencedorType',
    grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLeilaoVencedorRequest,
        gateway_pb2.OnLeilaoVencedorResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLeilaoVencedorRequest,
        gateway_pb2.OnLeilaoVencedorResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLeilaoVencedorRequest,
        gateway_pb2.OnLeilaoVencedorResponse,
    ],
)

_GatewayOnLinkPagamentoType = typing_extensions.TypeVar(
    '_GatewayOnLinkPagamentoType',
    grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLinkPagamentoRequest,
        gateway_pb2.OnLinkPagamentoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLinkPagamentoRequest,
        gateway_pb2.OnLinkPagamentoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnLinkPagamentoRequest,
        gateway_pb2.OnLinkPagamentoResponse,
    ],
)

_GatewayOnStatusPagamentoType = typing_extensions.TypeVar(
    '_GatewayOnStatusPagamentoType',
    grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnStatusPagamentoRequest,
        gateway_pb2.OnStatusPagamentoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnStatusPagamentoRequest,
        gateway_pb2.OnStatusPagamentoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        gateway_pb2.OnStatusPagamentoRequest,
        gateway_pb2.OnStatusPagamentoResponse,
    ],
)

class GatewayStub(typing.Generic[_GatewayOnLanceValidadoType, _GatewayOnLanceInvalidadoType, _GatewayOnLeilaoVencedorType, _GatewayOnLinkPagamentoType, _GatewayOnStatusPagamentoType]):
    """
    Servico responsavel pela comunicacao com o front-end.
    """

    @typing.overload
    def __init__(self: GatewayStub[
        grpc.UnaryUnaryMultiCallable[
            gateway_pb2.OnLanceValidadoRequest,
            gateway_pb2.OnLanceValidadoResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            gateway_pb2.OnLanceInvalidadoRequest,
            gateway_pb2.OnLanceInvalidadoResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            gateway_pb2.OnLeilaoVencedorRequest,
            gateway_pb2.OnLeilaoVencedorResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            gateway_pb2.OnLinkPagamentoRequest,
            gateway_pb2.OnLinkPagamentoResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            gateway_pb2.OnStatusPagamentoRequest,
            gateway_pb2.OnStatusPagamentoResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: GatewayStub[
        grpc.aio.UnaryUnaryMultiCallable[
            gateway_pb2.OnLanceValidadoRequest,
            gateway_pb2.OnLanceValidadoResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            gateway_pb2.OnLanceInvalidadoRequest,
            gateway_pb2.OnLanceInvalidadoResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            gateway_pb2.OnLeilaoVencedorRequest,
            gateway_pb2.OnLeilaoVencedorResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            gateway_pb2.OnLinkPagamentoRequest,
            gateway_pb2.OnLinkPagamentoResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            gateway_pb2.OnStatusPagamentoRequest,
            gateway_pb2.OnStatusPagamentoResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    OnLanceValidado: _GatewayOnLanceValidadoType
    """Ao receber notificacao de lance validado"""

    OnLanceInvalidado: _GatewayOnLanceInvalidadoType
    """Ao receber notificacao de lance invalidado"""

    OnLeilaoVencedor: _GatewayOnLeilaoVencedorType
    """Ao receber notificacao de vencedor de um leilao"""

    OnLinkPagamento: _GatewayOnLinkPagamentoType
    """Ao receber notificacao de geracao de link de pagamento"""

    OnStatusPagamento: _GatewayOnStatusPagamentoType
    """Ao receber notificacao do status do pagamento"""

GatewayAsyncStub: typing_extensions.TypeAlias = GatewayStub[
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceValidadoRequest,
        gateway_pb2.OnLanceValidadoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLanceInvalidadoRequest,
        gateway_pb2.OnLanceInvalidadoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLeilaoVencedorRequest,
        gateway_pb2.OnLeilaoVencedorResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnLinkPagamentoRequest,
        gateway_pb2.OnLinkPagamentoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        gateway_pb2.OnStatusPagamentoRequest,
        gateway_pb2.OnStatusPagamentoResponse,
    ],
]

class GatewayServicer(metaclass=abc.ABCMeta):
    """
    Servico responsavel pela comunicacao com o front-end.
    """

    @abc.abstractmethod
    def OnLanceValidado(
        self,
        request: gateway_pb2.OnLanceValidadoRequest,
        context: _ServicerContext,
    ) -> typing.Union[gateway_pb2.OnLanceValidadoResponse, collections.abc.Awaitable[gateway_pb2.OnLanceValidadoResponse]]:
        """Ao receber notificacao de lance validado"""

    @abc.abstractmethod
    def OnLanceInvalidado(
        self,
        request: gateway_pb2.OnLanceInvalidadoRequest,
        context: _ServicerContext,
    ) -> typing.Union[gateway_pb2.OnLanceInvalidadoResponse, collections.abc.Awaitable[gateway_pb2.OnLanceInvalidadoResponse]]:
        """Ao receber notificacao de lance invalidado"""

    @abc.abstractmethod
    def OnLeilaoVencedor(
        self,
        request: gateway_pb2.OnLeilaoVencedorRequest,
        context: _ServicerContext,
    ) -> typing.Union[gateway_pb2.OnLeilaoVencedorResponse, collections.abc.Awaitable[gateway_pb2.OnLeilaoVencedorResponse]]:
        """Ao receber notificacao de vencedor de um leilao"""

    @abc.abstractmethod
    def OnLinkPagamento(
        self,
        request: gateway_pb2.OnLinkPagamentoRequest,
        context: _ServicerContext,
    ) -> typing.Union[gateway_pb2.OnLinkPagamentoResponse, collections.abc.Awaitable[gateway_pb2.OnLinkPagamentoResponse]]:
        """Ao receber notificacao de geracao de link de pagamento"""

    @abc.abstractmethod
    def OnStatusPagamento(
        self,
        request: gateway_pb2.OnStatusPagamentoRequest,
        context: _ServicerContext,
    ) -> typing.Union[gateway_pb2.OnStatusPagamentoResponse, collections.abc.Awaitable[gateway_pb2.OnStatusPagamentoResponse]]:
        """Ao receber notificacao do status do pagamento"""

def add_GatewayServicer_to_server(servicer: GatewayServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
