# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\"M\n\x16OnLanceValidadoRequest\x12\x11\n\tleilao_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"%\n\x17OnLanceValidadoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"O\n\x18OnLanceInvalidadoRequest\x12\x11\n\tleilao_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\'\n\x19OnLanceInvalidadoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"^\n\x17OnLeilaoVencedorRequest\x12\x11\n\tleilao_id\x18\x01 \x01(\t\x12\x16\n\x0elance_vencedor\x18\x02 \x01(\t\x12\x18\n\x10\x63liente_vencedor\x18\x03 \x01(\t\"&\n\x18OnLeilaoVencedorResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"k\n\x16OnLinkPagamentoRequest\x12\x11\n\tleilao_id\x18\x01 \x01(\t\x12\x16\n\x0elance_vencedor\x18\x02 \x01(\t\x12\x18\n\x10\x63liente_vencedor\x18\x03 \x01(\t\x12\x0c\n\x04link\x18\x04 \x01(\t\"%\n\x17OnLinkPagamentoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"d\n\x18OnStatusPagamentoRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"\'\n\x19OnStatusPagamentoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x80\x03\n\x07Gateway\x12\x46\n\x0fOnLanceValidado\x12\x17.OnLanceValidadoRequest\x1a\x18.OnLanceValidadoResponse\"\x00\x12L\n\x11OnLanceInvalidado\x12\x19.OnLanceInvalidadoRequest\x1a\x1a.OnLanceInvalidadoResponse\"\x00\x12I\n\x10OnLeilaoVencedor\x12\x18.OnLeilaoVencedorRequest\x1a\x19.OnLeilaoVencedorResponse\"\x00\x12\x46\n\x0fOnLinkPagamento\x12\x17.OnLinkPagamentoRequest\x1a\x18.OnLinkPagamentoResponse\"\x00\x12L\n\x11OnStatusPagamento\x12\x19.OnStatusPagamentoRequest\x1a\x1a.OnStatusPagamentoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONLANCEVALIDADOREQUEST']._serialized_start=17
  _globals['_ONLANCEVALIDADOREQUEST']._serialized_end=94
  _globals['_ONLANCEVALIDADORESPONSE']._serialized_start=96
  _globals['_ONLANCEVALIDADORESPONSE']._serialized_end=133
  _globals['_ONLANCEINVALIDADOREQUEST']._serialized_start=135
  _globals['_ONLANCEINVALIDADOREQUEST']._serialized_end=214
  _globals['_ONLANCEINVALIDADORESPONSE']._serialized_start=216
  _globals['_ONLANCEINVALIDADORESPONSE']._serialized_end=255
  _globals['_ONLEILAOVENCEDORREQUEST']._serialized_start=257
  _globals['_ONLEILAOVENCEDORREQUEST']._serialized_end=351
  _globals['_ONLEILAOVENCEDORRESPONSE']._serialized_start=353
  _globals['_ONLEILAOVENCEDORRESPONSE']._serialized_end=391
  _globals['_ONLINKPAGAMENTOREQUEST']._serialized_start=393
  _globals['_ONLINKPAGAMENTOREQUEST']._serialized_end=500
  _globals['_ONLINKPAGAMENTORESPONSE']._serialized_start=502
  _globals['_ONLINKPAGAMENTORESPONSE']._serialized_end=539
  _globals['_ONSTATUSPAGAMENTOREQUEST']._serialized_start=541
  _globals['_ONSTATUSPAGAMENTOREQUEST']._serialized_end=641
  _globals['_ONSTATUSPAGAMENTORESPONSE']._serialized_start=643
  _globals['_ONSTATUSPAGAMENTORESPONSE']._serialized_end=682
  _globals['_GATEWAY']._serialized_start=685
  _globals['_GATEWAY']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
