"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OnLanceValidadoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILAO_ID_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    leilao_id: builtins.str
    client_id: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        leilao_id: builtins.str = ...,
        client_id: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id", "leilao_id", b"leilao_id", "value", b"value"]) -> None: ...

Global___OnLanceValidadoRequest: typing_extensions.TypeAlias = OnLanceValidadoRequest

@typing.final
class OnLanceValidadoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "ok", b"ok"]) -> None: ...

Global___OnLanceValidadoResponse: typing_extensions.TypeAlias = OnLanceValidadoResponse

@typing.final
class OnLanceInvalidadoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILAO_ID_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    leilao_id: builtins.str
    client_id: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        leilao_id: builtins.str = ...,
        client_id: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id", "leilao_id", b"leilao_id", "value", b"value"]) -> None: ...

Global___OnLanceInvalidadoRequest: typing_extensions.TypeAlias = OnLanceInvalidadoRequest

@typing.final
class OnLanceInvalidadoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "ok", b"ok"]) -> None: ...

Global___OnLanceInvalidadoResponse: typing_extensions.TypeAlias = OnLanceInvalidadoResponse

@typing.final
class OnLeilaoVencedorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILAO_ID_FIELD_NUMBER: builtins.int
    LANCE_VENCEDOR_FIELD_NUMBER: builtins.int
    CLIENTE_VENCEDOR_FIELD_NUMBER: builtins.int
    leilao_id: builtins.str
    lance_vencedor: builtins.str
    cliente_vencedor: builtins.str
    def __init__(
        self,
        *,
        leilao_id: builtins.str = ...,
        lance_vencedor: builtins.str = ...,
        cliente_vencedor: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cliente_vencedor", b"cliente_vencedor", "lance_vencedor", b"lance_vencedor", "leilao_id", b"leilao_id"]) -> None: ...

Global___OnLeilaoVencedorRequest: typing_extensions.TypeAlias = OnLeilaoVencedorRequest

@typing.final
class OnLeilaoVencedorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "ok", b"ok"]) -> None: ...

Global___OnLeilaoVencedorResponse: typing_extensions.TypeAlias = OnLeilaoVencedorResponse

@typing.final
class OnLinkPagamentoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILAO_ID_FIELD_NUMBER: builtins.int
    LANCE_VENCEDOR_FIELD_NUMBER: builtins.int
    CLIENTE_VENCEDOR_FIELD_NUMBER: builtins.int
    LINK_FIELD_NUMBER: builtins.int
    leilao_id: builtins.str
    lance_vencedor: builtins.str
    cliente_vencedor: builtins.str
    link: builtins.str
    def __init__(
        self,
        *,
        leilao_id: builtins.str = ...,
        lance_vencedor: builtins.str = ...,
        cliente_vencedor: builtins.str = ...,
        link: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cliente_vencedor", b"cliente_vencedor", "lance_vencedor", b"lance_vencedor", "leilao_id", b"leilao_id", "link", b"link"]) -> None: ...

Global___OnLinkPagamentoRequest: typing_extensions.TypeAlias = OnLinkPagamentoRequest

@typing.final
class OnLinkPagamentoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "ok", b"ok"]) -> None: ...

Global___OnLinkPagamentoResponse: typing_extensions.TypeAlias = OnLinkPagamentoResponse

@typing.final
class OnStatusPagamentoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    TRANSACTION_ID_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    value: builtins.str
    status: builtins.str
    transaction_id: builtins.str
    client_id: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
        status: builtins.str = ...,
        transaction_id: builtins.str = ...,
        client_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id", "status", b"status", "transaction_id", b"transaction_id", "value", b"value"]) -> None: ...

Global___OnStatusPagamentoRequest: typing_extensions.TypeAlias = OnStatusPagamentoRequest

@typing.final
class OnStatusPagamentoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "ok", b"ok"]) -> None: ...

Global___OnStatusPagamentoResponse: typing_extensions.TypeAlias = OnStatusPagamentoResponse
