"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import lance_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_LanceOnLanceType = typing_extensions.TypeVar(
    '_LanceOnLanceType',
    grpc.UnaryUnaryMultiCallable[
        lance_pb2.OnLanceRequest,
        lance_pb2.OnLanceResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        lance_pb2.OnLanceRequest,
        lance_pb2.OnLanceResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        lance_pb2.OnLanceRequest,
        lance_pb2.OnLanceResponse,
    ],
)

_LanceOnInitLeilaoType = typing_extensions.TypeVar(
    '_LanceOnInitLeilaoType',
    grpc.UnaryUnaryMultiCallable[
        lance_pb2.OnInitLeilaoRequest,
        lance_pb2.OnInitLeilaoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        lance_pb2.OnInitLeilaoRequest,
        lance_pb2.OnInitLeilaoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        lance_pb2.OnInitLeilaoRequest,
        lance_pb2.OnInitLeilaoResponse,
    ],
)

_LanceOnEndLeilaoType = typing_extensions.TypeVar(
    '_LanceOnEndLeilaoType',
    grpc.UnaryUnaryMultiCallable[
        lance_pb2.OnEndLeilaoRequest,
        lance_pb2.OnEndLeilaoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        lance_pb2.OnEndLeilaoRequest,
        lance_pb2.OnEndLeilaoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        lance_pb2.OnEndLeilaoRequest,
        lance_pb2.OnEndLeilaoResponse,
    ],
)

class LanceStub(typing.Generic[_LanceOnLanceType, _LanceOnInitLeilaoType, _LanceOnEndLeilaoType]):
    """
    / Servico responsavel pelo gerenciamento dos lances.
    """

    @typing.overload
    def __init__(self: LanceStub[
        grpc.UnaryUnaryMultiCallable[
            lance_pb2.OnLanceRequest,
            lance_pb2.OnLanceResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            lance_pb2.OnInitLeilaoRequest,
            lance_pb2.OnInitLeilaoResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            lance_pb2.OnEndLeilaoRequest,
            lance_pb2.OnEndLeilaoResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: LanceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            lance_pb2.OnLanceRequest,
            lance_pb2.OnLanceResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            lance_pb2.OnInitLeilaoRequest,
            lance_pb2.OnInitLeilaoResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            lance_pb2.OnEndLeilaoRequest,
            lance_pb2.OnEndLeilaoResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    OnLance: _LanceOnLanceType
    """Realiza um lance"""

    OnInitLeilao: _LanceOnInitLeilaoType
    """Ao receber notificacao de leilao iniciado"""

    OnEndLeilao: _LanceOnEndLeilaoType
    """Ao receber notificacao de leilao finalizado"""

LanceAsyncStub: typing_extensions.TypeAlias = LanceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        lance_pb2.OnLanceRequest,
        lance_pb2.OnLanceResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        lance_pb2.OnInitLeilaoRequest,
        lance_pb2.OnInitLeilaoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        lance_pb2.OnEndLeilaoRequest,
        lance_pb2.OnEndLeilaoResponse,
    ],
]

class LanceServicer(metaclass=abc.ABCMeta):
    """
    / Servico responsavel pelo gerenciamento dos lances.
    """

    @abc.abstractmethod
    def OnLance(
        self,
        request: lance_pb2.OnLanceRequest,
        context: _ServicerContext,
    ) -> typing.Union[lance_pb2.OnLanceResponse, collections.abc.Awaitable[lance_pb2.OnLanceResponse]]:
        """Realiza um lance"""

    @abc.abstractmethod
    def OnInitLeilao(
        self,
        request: lance_pb2.OnInitLeilaoRequest,
        context: _ServicerContext,
    ) -> typing.Union[lance_pb2.OnInitLeilaoResponse, collections.abc.Awaitable[lance_pb2.OnInitLeilaoResponse]]:
        """Ao receber notificacao de leilao iniciado"""

    @abc.abstractmethod
    def OnEndLeilao(
        self,
        request: lance_pb2.OnEndLeilaoRequest,
        context: _ServicerContext,
    ) -> typing.Union[lance_pb2.OnEndLeilaoResponse, collections.abc.Awaitable[lance_pb2.OnEndLeilaoResponse]]:
        """Ao receber notificacao de leilao finalizado"""

def add_LanceServicer_to_server(servicer: LanceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
