# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lance_pb2 as lance__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LanceStub(object):
    """
    / Servico responsavel pelo gerenciamento dos lances.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnLance = channel.unary_unary(
                '/Lance/OnLance',
                request_serializer=lance__pb2.OnLanceRequest.SerializeToString,
                response_deserializer=lance__pb2.OnLanceResponse.FromString,
                _registered_method=True)
        self.OnInitLeilao = channel.unary_unary(
                '/Lance/OnInitLeilao',
                request_serializer=lance__pb2.OnInitLeilaoRequest.SerializeToString,
                response_deserializer=lance__pb2.OnInitLeilaoResponse.FromString,
                _registered_method=True)
        self.OnEndLeilao = channel.unary_unary(
                '/Lance/OnEndLeilao',
                request_serializer=lance__pb2.OnEndLeilaoRequest.SerializeToString,
                response_deserializer=lance__pb2.OnEndLeilaoResponse.FromString,
                _registered_method=True)


class LanceServicer(object):
    """
    / Servico responsavel pelo gerenciamento dos lances.

    """

    def OnLance(self, request, context):
        """Realiza um lance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnInitLeilao(self, request, context):
        """Ao receber notificacao de leilao iniciado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnEndLeilao(self, request, context):
        """Ao receber notificacao de leilao finalizado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnLance': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLance,
                    request_deserializer=lance__pb2.OnLanceRequest.FromString,
                    response_serializer=lance__pb2.OnLanceResponse.SerializeToString,
            ),
            'OnInitLeilao': grpc.unary_unary_rpc_method_handler(
                    servicer.OnInitLeilao,
                    request_deserializer=lance__pb2.OnInitLeilaoRequest.FromString,
                    response_serializer=lance__pb2.OnInitLeilaoResponse.SerializeToString,
            ),
            'OnEndLeilao': grpc.unary_unary_rpc_method_handler(
                    servicer.OnEndLeilao,
                    request_deserializer=lance__pb2.OnEndLeilaoRequest.FromString,
                    response_serializer=lance__pb2.OnEndLeilaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Lance', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Lance(object):
    """
    / Servico responsavel pelo gerenciamento dos lances.

    """

    @staticmethod
    def OnLance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lance/OnLance',
            lance__pb2.OnLanceRequest.SerializeToString,
            lance__pb2.OnLanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnInitLeilao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lance/OnInitLeilao',
            lance__pb2.OnInitLeilaoRequest.SerializeToString,
            lance__pb2.OnInitLeilaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnEndLeilao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lance/OnEndLeilao',
            lance__pb2.OnEndLeilaoRequest.SerializeToString,
            lance__pb2.OnEndLeilaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
