"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OnLanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILAO_ID_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    leilao_id: builtins.str
    client_id: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        leilao_id: builtins.str = ...,
        client_id: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id", "leilao_id", b"leilao_id", "value", b"value"]) -> None: ...

Global___OnLanceRequest: typing_extensions.TypeAlias = OnLanceRequest

@typing.final
class OnLanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

Global___OnLanceResponse: typing_extensions.TypeAlias = OnLanceResponse

@typing.final
class OnInitLeilaoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    id: builtins.str
    description: builtins.str
    start: builtins.float
    end: builtins.float
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        description: builtins.str = ...,
        start: builtins.float = ...,
        end: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "end", b"end", "id", b"id", "start", b"start"]) -> None: ...

Global___OnInitLeilaoRequest: typing_extensions.TypeAlias = OnInitLeilaoRequest

@typing.final
class OnInitLeilaoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

Global___OnInitLeilaoResponse: typing_extensions.TypeAlias = OnInitLeilaoResponse

@typing.final
class OnEndLeilaoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

Global___OnEndLeilaoRequest: typing_extensions.TypeAlias = OnEndLeilaoRequest

@typing.final
class OnEndLeilaoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    LEILAO_ID_FIELD_NUMBER: builtins.int
    CLIENTE_VENCEDOR_FIELD_NUMBER: builtins.int
    LANCE_VENCEDOR_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    leilao_id: builtins.str
    cliente_vencedor: builtins.str
    lance_vencedor: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        leilao_id: builtins.str = ...,
        cliente_vencedor: builtins.str = ...,
        lance_vencedor: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cliente_vencedor", b"cliente_vencedor", "lance_vencedor", b"lance_vencedor", "leilao_id", b"leilao_id", "ok", b"ok"]) -> None: ...

Global___OnEndLeilaoResponse: typing_extensions.TypeAlias = OnEndLeilaoResponse
