# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import leilao_pb2 as leilao__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in leilao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeilaoStub(object):
    """/ 
    / Servico responsavel pelo gerenciamento de leiloes.
    /
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLeiloes = channel.unary_unary(
                '/Leilao/GetLeiloes',
                request_serializer=leilao__pb2.GetLeiloesRequest.SerializeToString,
                response_deserializer=leilao__pb2.GetLeiloesResponse.FromString,
                _registered_method=True)
        self.CreateLeilao = channel.unary_unary(
                '/Leilao/CreateLeilao',
                request_serializer=leilao__pb2.CreateLeilaoRequest.SerializeToString,
                response_deserializer=leilao__pb2.CreateLeilaoResponse.FromString,
                _registered_method=True)


class LeilaoServicer(object):
    """/ 
    / Servico responsavel pelo gerenciamento de leiloes.
    /
    """

    def GetLeiloes(self, request, context):
        """Carrega todos os leiloes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLeilao(self, request, context):
        """Cria um leilao
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeilaoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLeiloes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeiloes,
                    request_deserializer=leilao__pb2.GetLeiloesRequest.FromString,
                    response_serializer=leilao__pb2.GetLeiloesResponse.SerializeToString,
            ),
            'CreateLeilao': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLeilao,
                    request_deserializer=leilao__pb2.CreateLeilaoRequest.FromString,
                    response_serializer=leilao__pb2.CreateLeilaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Leilao', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Leilao', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Leilao(object):
    """/ 
    / Servico responsavel pelo gerenciamento de leiloes.
    /
    """

    @staticmethod
    def GetLeiloes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Leilao/GetLeiloes',
            leilao__pb2.GetLeiloesRequest.SerializeToString,
            leilao__pb2.GetLeiloesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLeilao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Leilao/CreateLeilao',
            leilao__pb2.CreateLeilaoRequest.SerializeToString,
            leilao__pb2.CreateLeilaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
