"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LeilaoInstance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    description: builtins.str
    value: builtins.float
    start: builtins.str
    end: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        value: builtins.float = ...,
        start: builtins.str = ...,
        end: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "end", b"end", "id", b"id", "name", b"name", "start", b"start", "value", b"value"]) -> None: ...

Global___LeilaoInstance: typing_extensions.TypeAlias = LeilaoInstance

@typing.final
class GetLeiloesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetLeiloesRequest: typing_extensions.TypeAlias = GetLeiloesRequest

@typing.final
class GetLeiloesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILOES_FIELD_NUMBER: builtins.int
    @property
    def leiloes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___LeilaoInstance]: ...
    def __init__(
        self,
        *,
        leiloes: collections.abc.Iterable[Global___LeilaoInstance] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["leiloes", b"leiloes"]) -> None: ...

Global___GetLeiloesResponse: typing_extensions.TypeAlias = GetLeiloesResponse

@typing.final
class CreateLeilaoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str
    value: builtins.float
    start: builtins.int
    end: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        value: builtins.float = ...,
        start: builtins.int = ...,
        end: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "end", b"end", "name", b"name", "start", b"start", "value", b"value"]) -> None: ...

Global___CreateLeilaoRequest: typing_extensions.TypeAlias = CreateLeilaoRequest

@typing.final
class CreateLeilaoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

Global___CreateLeilaoResponse: typing_extensions.TypeAlias = CreateLeilaoResponse
