"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import leilao_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_LeilaoGetLeiloesType = typing_extensions.TypeVar(
    '_LeilaoGetLeiloesType',
    grpc.UnaryUnaryMultiCallable[
        leilao_pb2.GetLeiloesRequest,
        leilao_pb2.GetLeiloesResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        leilao_pb2.GetLeiloesRequest,
        leilao_pb2.GetLeiloesResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        leilao_pb2.GetLeiloesRequest,
        leilao_pb2.GetLeiloesResponse,
    ],
)

_LeilaoCreateLeilaoType = typing_extensions.TypeVar(
    '_LeilaoCreateLeilaoType',
    grpc.UnaryUnaryMultiCallable[
        leilao_pb2.CreateLeilaoRequest,
        leilao_pb2.CreateLeilaoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        leilao_pb2.CreateLeilaoRequest,
        leilao_pb2.CreateLeilaoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        leilao_pb2.CreateLeilaoRequest,
        leilao_pb2.CreateLeilaoResponse,
    ],
)

class LeilaoStub(typing.Generic[_LeilaoGetLeiloesType, _LeilaoCreateLeilaoType]):
    """/ 
    / Servico responsavel pelo gerenciamento de leiloes.
    /
    """

    @typing.overload
    def __init__(self: LeilaoStub[
        grpc.UnaryUnaryMultiCallable[
            leilao_pb2.GetLeiloesRequest,
            leilao_pb2.GetLeiloesResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            leilao_pb2.CreateLeilaoRequest,
            leilao_pb2.CreateLeilaoResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: LeilaoStub[
        grpc.aio.UnaryUnaryMultiCallable[
            leilao_pb2.GetLeiloesRequest,
            leilao_pb2.GetLeiloesResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            leilao_pb2.CreateLeilaoRequest,
            leilao_pb2.CreateLeilaoResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    GetLeiloes: _LeilaoGetLeiloesType
    """Carrega todos os leiloes"""

    CreateLeilao: _LeilaoCreateLeilaoType
    """Cria um leilao"""

LeilaoAsyncStub: typing_extensions.TypeAlias = LeilaoStub[
    grpc.aio.UnaryUnaryMultiCallable[
        leilao_pb2.GetLeiloesRequest,
        leilao_pb2.GetLeiloesResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        leilao_pb2.CreateLeilaoRequest,
        leilao_pb2.CreateLeilaoResponse,
    ],
]

class LeilaoServicer(metaclass=abc.ABCMeta):
    """/ 
    / Servico responsavel pelo gerenciamento de leiloes.
    /
    """

    @abc.abstractmethod
    def GetLeiloes(
        self,
        request: leilao_pb2.GetLeiloesRequest,
        context: _ServicerContext,
    ) -> typing.Union[leilao_pb2.GetLeiloesResponse, collections.abc.Awaitable[leilao_pb2.GetLeiloesResponse]]:
        """Carrega todos os leiloes"""

    @abc.abstractmethod
    def CreateLeilao(
        self,
        request: leilao_pb2.CreateLeilaoRequest,
        context: _ServicerContext,
    ) -> typing.Union[leilao_pb2.CreateLeilaoResponse, collections.abc.Awaitable[leilao_pb2.CreateLeilaoResponse]]:
        """Cria um leilao"""

def add_LeilaoServicer_to_server(servicer: LeilaoServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
