# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: leilao.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'leilao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cleilao.proto\"j\n\x0eLeilaoInstance\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x12\r\n\x05start\x18\x05 \x01(\t\x12\x0b\n\x03\x65nd\x18\x06 \x01(\t\"\x13\n\x11GetLeiloesRequest\"6\n\x12GetLeiloesResponse\x12 \n\x07leiloes\x18\x01 \x03(\x0b\x32\x0f.LeilaoInstance\"c\n\x13\x43reateLeilaoRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x12\r\n\x05start\x18\x05 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x06 \x01(\x05\"\"\n\x14\x43reateLeilaoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x80\x01\n\x06Leilao\x12\x37\n\nGetLeiloes\x12\x12.GetLeiloesRequest\x1a\x13.GetLeiloesResponse\"\x00\x12=\n\x0c\x43reateLeilao\x12\x14.CreateLeilaoRequest\x1a\x15.CreateLeilaoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leilao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEILAOINSTANCE']._serialized_start=16
  _globals['_LEILAOINSTANCE']._serialized_end=122
  _globals['_GETLEILOESREQUEST']._serialized_start=124
  _globals['_GETLEILOESREQUEST']._serialized_end=143
  _globals['_GETLEILOESRESPONSE']._serialized_start=145
  _globals['_GETLEILOESRESPONSE']._serialized_end=199
  _globals['_CREATELEILAOREQUEST']._serialized_start=201
  _globals['_CREATELEILAOREQUEST']._serialized_end=300
  _globals['_CREATELEILAORESPONSE']._serialized_start=302
  _globals['_CREATELEILAORESPONSE']._serialized_end=336
  _globals['_LEILAO']._serialized_start=339
  _globals['_LEILAO']._serialized_end=467
# @@protoc_insertion_point(module_scope)
