"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OnWinnerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEILAO_ID_FIELD_NUMBER: builtins.int
    LANCE_VENCEDOR_FIELD_NUMBER: builtins.int
    CLIENTE_VENCEDOR_FIELD_NUMBER: builtins.int
    leilao_id: builtins.str
    lance_vencedor: builtins.str
    cliente_vencedor: builtins.str
    def __init__(
        self,
        *,
        leilao_id: builtins.str = ...,
        lance_vencedor: builtins.str = ...,
        cliente_vencedor: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cliente_vencedor", b"cliente_vencedor", "lance_vencedor", b"lance_vencedor", "leilao_id", b"leilao_id"]) -> None: ...

Global___OnWinnerRequest: typing_extensions.TypeAlias = OnWinnerRequest

@typing.final
class OnWinnerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "ok", b"ok"]) -> None: ...

Global___OnWinnerResponse: typing_extensions.TypeAlias = OnWinnerResponse
