"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import pagamento_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_PagamentoOnWinnerType = typing_extensions.TypeVar(
    '_PagamentoOnWinnerType',
    grpc.UnaryUnaryMultiCallable[
        pagamento_pb2.OnWinnerRequest,
        pagamento_pb2.OnWinnerResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        pagamento_pb2.OnWinnerRequest,
        pagamento_pb2.OnWinnerResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        pagamento_pb2.OnWinnerRequest,
        pagamento_pb2.OnWinnerResponse,
    ],
)

class PagamentoStub(typing.Generic[_PagamentoOnWinnerType]):
    """
    Servico responsavel pelo gerenciamento dos pagamentos.
    """

    @typing.overload
    def __init__(self: PagamentoStub[
        grpc.UnaryUnaryMultiCallable[
            pagamento_pb2.OnWinnerRequest,
            pagamento_pb2.OnWinnerResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: PagamentoStub[
        grpc.aio.UnaryUnaryMultiCallable[
            pagamento_pb2.OnWinnerRequest,
            pagamento_pb2.OnWinnerResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    OnWinner: _PagamentoOnWinnerType
    """Ao receber notificacao de vencedor de um leilao"""

PagamentoAsyncStub: typing_extensions.TypeAlias = PagamentoStub[
    grpc.aio.UnaryUnaryMultiCallable[
        pagamento_pb2.OnWinnerRequest,
        pagamento_pb2.OnWinnerResponse,
    ],
]

class PagamentoServicer(metaclass=abc.ABCMeta):
    """
    Servico responsavel pelo gerenciamento dos pagamentos.
    """

    @abc.abstractmethod
    def OnWinner(
        self,
        request: pagamento_pb2.OnWinnerRequest,
        context: _ServicerContext,
    ) -> typing.Union[pagamento_pb2.OnWinnerResponse, collections.abc.Awaitable[pagamento_pb2.OnWinnerResponse]]:
        """Ao receber notificacao de vencedor de um leilao"""

def add_PagamentoServicer_to_server(servicer: PagamentoServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
